### ISSUE TITLE
Error building on ubuntu 

### ISSUE THREAD

**Issue by psudo-student** [physical-computation/narvie#13]
error[E0658]: macro dbg! is unstable (see issue #54306)                         
   --> /home/team4/.cargo/registry/src/github.com-1ecc6299db9ec823/narvie-cli-0.3.2/src/lib/instruction.rs:535:13
    |                                                                           
535 |             dbg!(memory_location);                                        
    |             ^^^^^^^^^^^^^^^^^^^^^^                                        
                                                                                
error: aborting due to previous error                                           
                                                                                
For more information about this error, try `rustc --explain E0658`.             
error: failed to compile `narvie-cli v0.3.2`, intermediate artifacts can be found at `/tmp/cargo-installNfHItu`

Caused by:
  Could not compile `narvie-cli`.

To learn more, run the command again with --verbose.

**Comment by harrysarson** [comment]
Hi, would it be possible to post your rust version? (The output of `rustc --version`.)

**Comment by psudo-student** [comment]
rustc 1.31.0

**Comment by harrysarson** [comment]
Is it possible to upgrade you version of rust? I know that rust v1.34 works

**Comment by harrysarson** [comment]
Saying that, this `dbg!` macro probably should not have made it into the release of narvie

**Comment by psudo-student** [comment]
The offending line is removed, but somehow the same error is occuring:

error[E0658]: macro dbg! is unstable (see issue #54306)                         
   --> /home/team2/.cargo/registry/src/github.com-1ecc6299db9ec823/narvie-cli-0.3.2/src/lib/instruction.rs:535:13
    |                                                                           
535 |             dbg!(memory_location);                                        
    |             ^^^^^^^^^^^^^^^^^^^^^^                                        
                                                                                
error: aborting due to previous error                                           
                                                                                
For more information about this error, try `rustc --explain E0658`.             
error: failed to compile `narvie-cli v0.3.2`, intermediate artifacts can be found at `/tmp/cargo-installyd1rIk`

Caused by:
  Could not compile `narvie-cli`.

**Comment by psudo-student** [comment]
It's like it's been cached somewhere on the remote

**Comment by psudo-student** [comment]
This is from a totally fresh clone on a totally fresh machine

**Comment by psudo-student** [comment]
> Is it possible to upgrade you version of rust? I know that rust v1.34 works

I can confirm v1.34 does not have any issues, so we can use that as a workaround if needed, would be nice to resolve anyway

**Comment by harrysarson** [comment]
I haven't published a new version but if you clone this repository and run `cargo build --bin narvie-cli` that might work. I think I will add a note to the readme that we only support the latest stable version of rust as that is what we run our tests against in CI.

**Comment by harrysarson** [comment]
I have added the note to the readme, if there is anything else we can do to help please let me know!
